# Example Story Generation Configuration

# Model settings
model_name: "Qwen/Qwen2.5-3B-Instruct"
device: "auto"  # auto, cuda, cpu

# Generation parameters
generation:
  batch_size: 8
  max_new_tokens: 512
  temperature: 0.8
  top_p: 0.9
  do_sample: true
  repetition_penalty: 1.1
  use_cache: true

# Data paths
vocabulary_path: "training/synthetic_data_generation/vocabulary.json"
story_features_path: "docs/story_features.json"
conversation_examples_path: "training/synthetic_data_generation/example_conversation.txt"

# Generation settings
num_stories: 100  # Start with a small number for testing
k_shot_count: 2
use_k_shot: true
ensure_diversity: true

# Output settings
output_path: "generated_stories.jsonl"
save_intermediate: true
intermediate_save_interval: 50

# Validation settings
validate_stories: true
min_words: 50
max_words: 300

# Logging
log_level: "INFO"
